CREATE TABLE REPORT
(
    ID           BIGINT IDENTITY NOT NULL PRIMARY KEY,
    REFID        BIGINT,
    NAME         VARCHAR(100),
    AGE          BIGINT,
    PLAYFULLNESS VARCHAR(32),
    READYTOADOPT VARCHAR(32)
);